### ISSUE TITLE
Split out Test plugin into separate, highly cohesive plugins

### ISSUE THREAD

**Issue by shaynevanasperen** [shaynevanasperen/PowerTasks#5]
The omission of dependencies in the nuspec file was purely because initially, PowerTasks (previously [psakify](https://github.com/SeatwaveOpenSource/psakify)) was a monolithic package that contained the scripts for all the bundled tasks, and because consumers of the package would not always require all the functionality, we didn't want to require the installation of supporting NuGet packages that would never be used. Now that the bundled tasks are being delivered as plugin packages, it makes sense to add the dependencies to the respective plugin NuGet packages' nuspec files.

However, if we do this for the `Test` plugin, then we would be forcing the consumer to install `Machine.Specifications.Runner.Console`, `NUnit.Runners`, `SpecFlow` and `Chutzpah`. Additionally, we would have to bundle the `BrowserStackLocal.exe` which is likely to become outdated pretty quickly. Also, who are we to assume that all consumers of the `Test` plugin are going to want to use BrowserStack for their SpecFlow tests? On top of this, due to a recent collaboration on a shared project I know first hand that the `Test` plugin is no longer working as-is for that project due to custom requirements. These facts lead me to conclude that we were overly optimistic in thinking that we could write a "one size fits all" test plugin for PowerTasks, as we quickly outgrew the supported functionality it provided and now use a customised test task in the consuming project.

The current state of the `Test` plugin is a bit of a mess, with an implicit dependency on the `Compile` plugin, and is therfore a prime candidate for refactoring (or preferably outright deprecation). In order to achieve loose coupling and high cohesion, the plugins should all be very focused and adhere to SRP. This will enable a modular design that is easily pluggable and suitable for a wide audience.

There is concern about being able to call `pt test`, instead of `pt unittest, jstest, acceptancetest` which is valid, but due to the flexibility of `Invoke-Build` it can easily be achieved by using composition, through defining top-level tasks in the consuming project such as this:

```
task Test UnitTest, JsTest, AcceptanceTest

task ci Clean, Version, Compile, Test, Pack, Push

task dev Clean, Compile, Test
```

I propose that we split out the various test types into separate, highly cohesive plugins, each doing only one thing. These should have very specific names, such as `MSpec`, `NUnit`, `SpecFlow`, `Chutzpah`, etc. thus leaving room for a possbile future `xUnit` one (and others). Once that is done, then we can add the relevant dependencies to the respective plugins' nuspec files. It would also be nice if we could break the implicit dependency on the `Compile` plugin, so that we can individually compile test projects and avoid compiling any test projects if we only want to compile the main project.

**Comment by Kennethtruyers** [comment]
One thing to note about the dependencies:

Since the plugins are installed into the main project, it doesn't always make sense to add dependencies there. For example: it does make sense to add test runners as a dependency, but it doesn't make sense to add mspec as a dependency.

**Comment by Kennethtruyers** [comment]
This is fixed in https://github.com/shaynevanasperen/PowerTasks/pull/14
